# Generated by Django 5.2.9 on 2025-12-26 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_local', models.CharField(blank=True, default='', max_length=255)),
                ('version_nickname', models.CharField(blank=True, default='', max_length=255)),
                ('objectid', models.PositiveIntegerField(db_index=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_playing_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_playing_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('STANDALONE', 'Standalone'), ('EXPANSION', 'Expansion'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.owner')),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='owners',
            field=models.ManyToManyField(related_name='games', through='accounts.OwnerInventory', to='accounts.owner'),
        ),
        migrations.CreateModel(
            name='UserGameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='accounts.boardgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ownerinventory',
            constraint=models.UniqueConstraint(fields=('owner', 'game'), name='uniq_owner_game'),
        ),
        migrations.AddConstraint(
            model_name='boardgame',
            constraint=models.UniqueConstraint(fields=('objectid', 'title'), name='uniq_objectid_version'),
        ),
        migrations.AddConstraint(
            model_name='usergamestatus',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='uniq_user_game_status'),
        ),
    ]
